-- CreateEnum
CREATE TYPE "DeveloperRoles" AS ENUM ('FRONTEND_DEVELOPER', 'BACKEND_DEVELOPER', 'FULLSTACK_DEVELOPER');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "devRole" "DeveloperRoles" NOT NULL DEFAULT 'FULLSTACK_DEVELOPER';
